name: Build CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install and build the frontend
      - name: Install and build frontend
        run: |
          cd ui/frontend
          yarn install
          yarn run build

      # Set up Rust environment
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      # Build Rust server
      - name: Build Rust server
        run: |
          cd ui
          cargo build --release

      # Build the compiler containers
      - name: Build compiler tools
        run: |
          cd compiler
          chmod +x build.sh
          ./build.sh

